### ISSUE TITLE
Code review 6-12-2024

### ISSUE THREAD

**Issue by Ravirkt** [DivaniNL/fix-the-flow-interactive-website#21]
Goedemorgen, Hierbij onze feedback:

feedback:
- Comment voor de eerste regel code over de mediaquery;
- Duidelijke comments over de code;

positieve feedback :
- Je maakt gebruik van localstorage;

design review:
- Hover toevoegen op de button voor meer feedforward;
-  (positieve feedback)mooi dat de kleur en tekst veranderen
- Hij zou mooi zijn als er een animatie was als je op de knop drukt en een hover;

mvg,

@matthijs217, @irisvw, @ravirkt

**Comment by DivaniNL** [comment]
Hallo
Bedankt voor de feedback.
Ik heb een vraagje.
behalve de comment die mist betreft de mediaquery, kan je een voorbeeld geven op welk ander punt de comments duidelijker mogen(jullie feedback punt 2), dan pas ik het aan.

**Comment by DivaniNL** [comment]
https://github.com/DivaniNL/fix-the-flow-interactive-website/commit/349f0f3b1bf21541fa5b6db475d1dd1173a995f9
De media query comment is alvast toegevoegd.

**Comment by irisvw** [comment]
Had het nog voor je nagevraagd; punt 2 was positief bedoeld, we vonden je comments duidelijk :)

**Comment by DivaniNL** [comment]
https://github.com/DivaniNL/fix-the-flow-interactive-website/commit/538ecf048db275ba43ed658ab2254f56ba6124db
Animatie is toegevoegd.

Ook de feedforward is toegevoegd op de button voor de leeslijst als er een item actief is. Zie commit:
[Commit 201478f](https://github.com/DivaniNL/fix-the-flow-interactive-website/commit/201478fa1af5b935184a97b01dfd94a330e3aa18)
Er wordt nu voor 1 seconde (later opgehoogd naar 2 seconden) laten zien dat het item is toegevoegd. Daarna veranderd de tekst. Bij page load is de tijdelijke tekst niet te zien.
Hieronder de screenshots van de "added" en "active" state:

![Image](https://github.com/user-attachments/assets/14096383-0dea-4ee7-bfbc-91649a18623a)
![Image](https://github.com/user-attachments/assets/8fbaa4a4-9f36-4b28-97a7-de91f132c5d9)
.

Volgensmij heb ik alle punten opgelost. Mochten er nog zaken zijn, dan kan je het issue heropenen : )
