### ISSUE TITLE
Feedforward toevoegen-aan-leeslijst knop 

### ISSUE THREAD

**Issue by KoopReynders** [DivaniNL/fix-the-flow-interactive-website#22]
Misschien kan je aan de knop ook het label toevoegen dat je daarmee het artikel weer uit de leeslijst kan halen. 
<img width="167" alt="image" src="https://github.com/user-attachments/assets/c72d74db-5c5e-467a-a0cc-74833b0789bb">

**Comment by DivaniNL** [comment]
Ik heb dit opgelost. Zie commit: 
[Commit 201478f](https://github.com/DivaniNL/fix-the-flow-interactive-website/commit/201478fa1af5b935184a97b01dfd94a330e3aa18)

**Comment by DivaniNL** [comment]
--> https://github.com/DivaniNL/fix-the-flow-interactive-website/commit/df3d445fac51657f1683da9dd428a4e381db8a37
Opgehoogd naar 2 seconde. 1 seconde was wel erg kort.

**Comment by DivaniNL** [comment]
![Image](https://github.com/user-attachments/assets/ca6f562a-11db-4145-a13f-8b7a35621372)
![Image](https://github.com/user-attachments/assets/fefc4f23-4721-417d-a8df-42f777558be5)

Hier zijn beide states te zien
