### ISSUE TITLE
Feedback leeslijst counter

### ISSUE THREAD

**Issue by KoopReynders** [DivaniNL/fix-the-flow-interactive-website#23]
Een animatie op de leeslijst counter als ene artikel is toegevoegd is mooie feedback voor de gebruiker!
Voorbeelden hiervan zie je ook wel bij online pizza bestellen en winkelmandjes.

**Comment by KoopReynders** [comment]
Je kan ook de tooltip even laten zien en dat die weer verdwijnt, dan heb je feedback op de toevoegen actie, en meteen feedforward dat d gebruiker daar de leeslijst kan zien.

**Comment by DivaniNL** [comment]
https://github.com/DivaniNL/fix-the-flow-interactive-website/commit/daf83bbb5eb39ea4b83c123fc829122b279e38de
gelijk even de titel en auteur in de tooltip omgedraaid. Dit was ook een puntje als wat ik me kan herinneren.
Zie hier het resultaat:
<img width="215" alt="Schermafbeelding 2024-12-06 om 19 33 28" src="https://github.com/user-attachments/assets/c189eb0d-59d0-4675-b9f1-3f9c53ce99b7">

**Comment by DivaniNL** [comment]
https://github.com/DivaniNL/fix-the-flow-interactive-website/commit/ebb99abb49012bb47aab7d4d35a26a5877d69286
De feedback is toegevoegd. ligt dit in lijn met wat je bedoelde?
